require("core.plugin_config.looks.colorscheme")
require("core.plugin_config.looks.dashboard-alpha")
require("core.plugin_config.looks.gitsigns")
require("core.plugin_config.looks.lualine")
require("core.plugin_config.looks.notify")
